import { yekan } from "@/core/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${yekan.className} max-w-[1440px] mx-auto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
