import TanstackProvider from "@/components/provider/TanstackProvider";
import "./globals.css";
import { yekan } from "@/core/utils/fonts";
import Header from "@/components/templates/layouts/Header";
import Footer from "@/components/templates/layouts/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" dir="rtl">
      <body
        className={`${yekan.className} mx-auto font-medium antialiased`}
      >
        <TanstackProvider>
          <Header />
          <main className="min-h-svh md:max-w-[1440px] mx-auto">{children}</main>
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
